#!/bin/bash

[[ -z $(dpkg -l | awk '{print$2}' | grep '^zsh$') ]] && apt update && apt install zsh fzf fd-find ripgrep ugrep bfs

if [[ ! -e "/$HOME/.zimrc" ]]; then
curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
fi

sed -i '/compinit/d' /$HOME/.zshrc
cat << EOF >| /$HOME/.zimrc
zmodule environment
zmodule git
zmodule input
zmodule termtitle
zmodule utility
zmodule prompt
zmodule duration-info
zmodule git-info
zmodule asciiship
zmodule completion
zmodule zsh-users/zsh-completions --fpath src
zmodule zsh-users/zsh-history-substring-search
zmodule zsh-users/zsh-autosuggestions
zmodule zsh-users/zsh-syntax-highlighting
zmodule zdharma-continuum/fast-syntax-highlighting

zmodule romkatv/powerlevel10k
zmodule fzf
zmodule Aloxaf/fzf-tab
zmodule supercrabtree/k
zmodule hlissner/zsh-autopair
zmodule pabloariasal/zfm
zmodule agkozak/zsh-z
EOF

